version: "2.2"
services:
  default:
    environment:
      - AWS_ACCESS_KEY_ID=default
      - AWS_SECRET_ACCESS_KEY=default
      - AWS_REGION=eu-west-2
      - AWS_ENDPOINT=http://localstack:4566
    links:
      - localstack:localstack
    depends_on:
      localstack:
        condition: service_healthy
    volumes:
      - "./terraform/.cache:/home/dojo/.terraform.d/plugin-cache"
  localstack:
    image: localstack/localstack:1.2.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,lambda,dynamodb,iam,apigateway,logs,sts,sqs,ssm
      - DEFAULT_REGION=eu-west-2
      - HOSTNAME_EXTERNAL=localhost
      - LAMBDA_CONTAINER_REGISTRY=mlupin/docker-lambda
      - LAMBDA_EXECUTOR=docker-reuse
      - DEBUG=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
