environment                  = "pre-prod"
account_id                   = "694282683086"
enable_session_auth          = false
cognito_domain_prefix        = "pre-prod-"
oidc_providers               = ["COGNITO"]
cis2_provider_oidc_issuer    = "https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_0UlxTpOj3"
cis2_provider_authorize_url  = "https://pre-prod-doc-store-user-pool.auth.eu-west-2.amazoncognito.com/oauth2/authorize"
cis2_provider_token_url      = "https://pre-prod-doc-store-user-pool.auth.eu-west-2.amazoncognito.com/oauth2/token"
cis2_provider_attributes_url = "https://pre-prod-doc-store-user-pool.auth.eu-west-2.amazoncognito.com/oauth2/userInfo"
cis2_provider_jwks_uri       = "https://cognito-idp.eu-west-2.amazonaws.com/eu-west-2_0UlxTpOj3/.well-known/jwks.json"
cis2_client_callback_urls    = []
cis2_client_signout_urls     = []
cognito_key_id               = "hkmsNYnD3kvYvyaOWcuqPT2K5lad8tT8mWZU1sF6n14="
pds_fhir_is_stubbed          = "false"
cloud_storage_security_agent_role_arn = "arn:aws:iam::694282683086:role/CloudStorageSecAgentRole-d2ixsle"
quarantine_bucket_name                = "cloudstoragesecquarantine-694282683086-eu-west-2"