package uk.nhs.digital.docstore.authoriser;

import static org.junit.jupiter.api.Assertions.*;

import java.util.Collections;
import org.json.JSONObject;
import org.junit.jupiter.api.Test;

class JSONDataExtractorTest {

    @Test
    void returnsSingularODSCode() {
        String odsCode = "A9A5A";
        String singleOrgUser =
                "{\n"
                        + "    \"uid\": \"555042709107\",\n"
                        + "    \"sub\": \"555042709107\",\n"
                        + "    \"nhsid_useruid\": \"555042709107\",\n"
                        + "    \"nhsid_nrbac_roles\": [\n"
                        + "        {\n"
                        + "            \"role_name\": \"\\\"Support\\\":\\\"Systems"
                        + " Support\\\":\\\"Systems Support Access Role\\\"\",\n"
                        + "            \"activities\": [\n"
                        + "                \"View Sensitive Results\",\n"
                        + "                \"View Detailed Health Records\",\n"
                        + "                \"Perform Clinical Coding\"\n"
                        + "            ],\n"
                        + "            \"person_orgid\": \"555042719109\",\n"
                        + "            \"person_roleid\": \"555042720102\",\n"
                        + "            \"role_code\": \"S8001:G8005:R8015\",\n"
                        + "            \"activity_codes\": [\n"
                        + "                \"B1666\",\n"
                        + "                \"B0360\",\n"
                        + "                \"B0790\"\n"
                        + "            ],\n"
                        + "            \"org_code\": \""
                        + odsCode
                        + "\"\n"
                        + "        }\n"
                        + "    ],\n"
                        + "    \"nhsid_user_orgs\": [\n"
                        + "        {\n"
                        + "            \"org_name\": \"NHSID DEV\",\n"
                        + "            \"org_code\": \""
                        + odsCode
                        + "\"\n"
                        + "        }\n"
                        + "    ],\n"
                        + "    \"name\": \"TestUserOne Caius Mr\",\n"
                        + "    \"given_name\": \"Caius\",\n"
                        + "    \"family_name\": \"TestUserOne\"\n"
                        + "}";
        var userInfo = new JSONObject(singleOrgUser);

        var dataExtractor = new JSONDataExtractor();
        var codes = dataExtractor.getOdsCodesFromUserInfo(userInfo);

        assert (codes.get(0)).equals(odsCode);
    }

    @Test
    void returnsMultipleODSCodes() {
        String odsCode0 = "A9A5A";
        String odsCode1 = "RBA";
        String odsCode2 = "B1B1B";
        String multipleOrgUser =
                "{\n"
                        + "    \"nhsid_useruid\": \"910000000001\",\n"
                        + "    \"name\": \"USERQ RANDOM Mr\",\n"
                        + "    \"nhsid_nrbac_roles\": [\n"
                        + "        {\n"
                        + "            \"org_code\": \""
                        + odsCode0
                        + "\",\n"
                        + "            \"person_orgid\": \"555254239107\",\n"
                        + "            \"person_roleid\": \"555254240100\",\n"
                        + "            \"role_code\": \"S8000:G8000:R8001\",\n"
                        + "            \"role_name\": \"\\\"Clinical\\\":\\\"Clinical"
                        + " Provision\\\":\\\"Nurse Access Role\\\"\"\n"
                        + "        },\n"
                        + "        {\n"
                        + "            \"org_code\": \""
                        + odsCode1
                        + "\",\n"
                        + "            \"person_orgid\": \"555254239107\",\n"
                        + "            \"person_roleid\": \"555254242102\",\n"
                        + "            \"role_code\": \"S8000:G8000:R8000\",\n"
                        + "            \"role_name\": \"\\\"Clinical\\\":\\\"Clinical"
                        + " Provision\\\":\\\"Clinical Practitioner Access Role\\\"\"\n"
                        + "        },\n"
                        + "        {\n"
                        + "            \"org_code\": \""
                        + odsCode2
                        + "\",\n"
                        + "            \"person_orgid\": \"555254239107\",\n"
                        + "            \"person_roleid\": \"555254241101\",\n"
                        + "            \"role_code\": \"S8000:G8000:R8003\",\n"
                        + "            \"role_name\": \"\\\"Clinical\\\":\\\"Clinical"
                        + " Provision\\\":\\\"Health Professional Access Role\\\"\"\n"
                        + "        }\n"
                        + "    ]\n"
                        + "}";
        var userInfo = new JSONObject(multipleOrgUser);

        var dataExtractor = new JSONDataExtractor();
        var codes = dataExtractor.getOdsCodesFromUserInfo(userInfo);

        assertTrue(codes.contains(odsCode0));
        assertTrue(codes.contains(odsCode1));
        assertTrue(codes.contains(odsCode2));
    }

    @Test
    void ignoresDuplicateODSCodes() {
        String singularCode = "A9A5A";
        String duplicatedCode = "B1B1B";
        String multipleOrgUser =
                "{\n"
                        + "    \"nhsid_useruid\": \"910000000001\",\n"
                        + "    \"name\": \"USERQ RANDOM Mr\",\n"
                        + "    \"nhsid_nrbac_roles\": [\n"
                        + "        {\n"
                        + "            \"org_code\": \""
                        + singularCode
                        + "\",\n"
                        + "            \"person_orgid\": \"555254239107\",\n"
                        + "            \"person_roleid\": \"555254240100\",\n"
                        + "            \"role_code\": \"S8000:G8000:R8001\",\n"
                        + "            \"role_name\": \"\\\"Clinical\\\":\\\"Clinical"
                        + " Provision\\\":\\\"Nurse Access Role\\\"\"\n"
                        + "        },\n"
                        + "        {\n"
                        + "            \"org_code\": \""
                        + duplicatedCode
                        + "\",\n"
                        + "            \"person_orgid\": \"555254239107\",\n"
                        + "            \"person_roleid\": \"555254242102\",\n"
                        + "            \"role_code\": \"S8000:G8000:R8000\",\n"
                        + "            \"role_name\": \"\\\"Clinical\\\":\\\"Clinical"
                        + " Provision\\\":\\\"Clinical Practitioner Access Role\\\"\"\n"
                        + "        },\n"
                        + "        {\n"
                        + "            \"org_code\": \""
                        + duplicatedCode
                        + "\",\n"
                        + "            \"person_orgid\": \"555254239107\",\n"
                        + "            \"person_roleid\": \"555254241101\",\n"
                        + "            \"role_code\": \"S8000:G8000:R8003\",\n"
                        + "            \"role_name\": \"\\\"Clinical\\\":\\\"Clinical"
                        + " Provision\\\":\\\"Health Professional Access Role\\\"\"\n"
                        + "        }\n"
                        + "    ]\n"
                        + "}";
        var userInfo = new JSONObject(multipleOrgUser);

        var dataExtractor = new JSONDataExtractor();
        var codes = dataExtractor.getOdsCodesFromUserInfo(userInfo);

        assertEquals(1, Collections.frequency(codes, singularCode));
        assertEquals(1, Collections.frequency(codes, duplicatedCode));
    }

    @Test
    void returnsAnEmptyArrayIfUserHasNoRoles() {
        String singleOrgUser =
                "{\n"
                        + "    \"uid\": \"555042709107\",\n"
                        + "    \"sub\": \"555042709107\",\n"
                        + "    \"nhsid_useruid\": \"555042709107\",\n"
                        + "    \"nhsid_nrbac_roles\": [\n"
                        + "    ],\n"
                        + "    \"nhsid_user_orgs\": [\n"
                        + "        {\n"
                        + "            \"org_name\": \"NHSID DEV\",\n"
                        + "            \"org_code\": \"A9A5A\"\n"
                        + "        }\n"
                        + "    ],\n"
                        + "    \"name\": \"TestUserOne Caius Mr\",\n"
                        + "    \"given_name\": \"Caius\",\n"
                        + "    \"family_name\": \"TestUserOne\"\n"
                        + "}";
        var userInfo = new JSONObject(singleOrgUser);

        var dataExtractor = new JSONDataExtractor();
        var codes = dataExtractor.getOdsCodesFromUserInfo(userInfo);

        assert (codes.isEmpty());
    }

    @Test
    void returnsGpOrgFromOrgData() {
        String roleCode = "RO76";
        var expectedName = "NHS ENGLAND - X26";
        String singleRoleOrg =
                "{\n"
                        + "    \"Organisation\": {\n"
                        + "        \"Name\": \"" + expectedName + "\",\n"
                        + "        \"Date\": [\n"
                        + "            {\n"
                        + "                \"Type\": \"Operational\",\n"
                        + "                \"Start\": \"2013-01-21\"\n"
                        + "            },\n"
                        + "            {\n"
                        + "                \"Type\": \"Legal\",\n"
                        + "                \"Start\": \"2013-04-01\"\n"
                        + "            }\n"
                        + "        ],\n"
                        + "        \"OrgId\": {\n"
                        + "            \"root\": \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "            \"extension\": \"X26\"\n"
                        + "        },\n"
                        + "        \"Status\": \"Active\",\n"
                        + "        \"LastChangeDate\": \"2023-01-31\",\n"
                        + "        \"orgRecordClass\": \"RC1\",\n"
                        + "        \"GeoLoc\": {\n"
                        + "            \"Location\": {\n"
                        + "                \"AddrLn1\": \"THE LEEDS GOVERNMENT HUB\",\n"
                        + "                \"AddrLn2\": \"7-8 WELLINGTON PLACE\",\n"
                        + "                \"Town\": \"LEEDS\",\n"
                        + "                \"PostCode\": \"LS1 4AP\",\n"
                        + "                \"Country\": \"ENGLAND\",\n"
                        + "                \"UPRN\": 72766088\n"
                        + "            }\n"
                        + "        },\n"
                        + "        \"Roles\": {\n"
                        + "            \"Role\": [\n"
                        + "                {\n"
                        + "                    \"id\": \""
                        + roleCode
                        + "\",\n"
                        + "                    \"uniqueRoleId\": 166234,\n"
                        + "                    \"primaryRole\": true,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2013-01-21\"\n"
                        + "                        },\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Active\"\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        },\n"
                        + "        \"Rels\": {\n"
                        + "            \"Rel\": [\n"
                        + "                {\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2013-01-21\"\n"
                        + "                        },\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Active\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"XDH\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO126\",\n"
                        + "                            \"uniqueRoleId\": 128996\n"
                        + "                        }\n"
                        + "                    },\n"
                        + "                    \"id\": \"RE3\",\n"
                        + "                    \"uniqueRelId\": 189272\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        },\n"
                        + "        \"Succs\": {\n"
                        + "            \"Succ\": [\n"
                        + "                {\n"
                        + "                    \"uniqueSuccId\": 36688,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Type\": \"Predecessor\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"X09\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO116\",\n"
                        + "                            \"uniqueRoleId\": 111933\n"
                        + "                        }\n"
                        + "                    }\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"uniqueSuccId\": 36589,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Type\": \"Predecessor\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"T1430\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO189\",\n"
                        + "                            \"uniqueRoleId\": 136318\n"
                        + "                        }\n"
                        + "                    }\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        }\n"
                        + "    }\n"
                        + "}";
        var orgData = new JSONObject(singleRoleOrg);

        var dataExtractor = new JSONDataExtractor();
        var roleCodes = dataExtractor.getProspectiveOrgs(orgData);

        assert (roleCodes.isPresent());
        ProspectiveOrg org = roleCodes.get();
        assert (org.getOrgName()).equals(expectedName);
        assert (roleCodes.get()
    }

    @Test
    void returnsPcseOrgFromOrgData() {
        String roleCode = "RO157";
        var expectedName = "NHS ENGLAND - X26";
        String singleRoleOrg =
                "{\n"
                        + "    \"Organisation\": {\n"
                        + "        \"Name\": \"" + expectedName + "\",\n"
                        + "        \"Date\": [\n"
                        + "            {\n"
                        + "                \"Type\": \"Operational\",\n"
                        + "                \"Start\": \"2013-01-21\"\n"
                        + "            },\n"
                        + "            {\n"
                        + "                \"Type\": \"Legal\",\n"
                        + "                \"Start\": \"2013-04-01\"\n"
                        + "            }\n"
                        + "        ],\n"
                        + "        \"OrgId\": {\n"
                        + "            \"root\": \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "            \"extension\": \"X26\"\n"
                        + "        },\n"
                        + "        \"Status\": \"Active\",\n"
                        + "        \"LastChangeDate\": \"2023-01-31\",\n"
                        + "        \"orgRecordClass\": \"RC1\",\n"
                        + "        \"GeoLoc\": {\n"
                        + "            \"Location\": {\n"
                        + "                \"AddrLn1\": \"THE LEEDS GOVERNMENT HUB\",\n"
                        + "                \"AddrLn2\": \"7-8 WELLINGTON PLACE\",\n"
                        + "                \"Town\": \"LEEDS\",\n"
                        + "                \"PostCode\": \"LS1 4AP\",\n"
                        + "                \"Country\": \"ENGLAND\",\n"
                        + "                \"UPRN\": 72766088\n"
                        + "            }\n"
                        + "        },\n"
                        + "        \"Roles\": {\n"
                        + "            \"Role\": [\n"
                        + "                {\n"
                        + "                    \"id\": \""
                        + roleCode
                        + "\",\n"
                        + "                    \"uniqueRoleId\": 166234,\n"
                        + "                    \"primaryRole\": true,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2013-01-21\"\n"
                        + "                        },\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Active\"\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        },\n"
                        + "        \"Rels\": {\n"
                        + "            \"Rel\": [\n"
                        + "                {\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2013-01-21\"\n"
                        + "                        },\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Active\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"XDH\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO126\",\n"
                        + "                            \"uniqueRoleId\": 128996\n"
                        + "                        }\n"
                        + "                    },\n"
                        + "                    \"id\": \"RE3\",\n"
                        + "                    \"uniqueRelId\": 189272\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        },\n"
                        + "        \"Succs\": {\n"
                        + "            \"Succ\": [\n"
                        + "                {\n"
                        + "                    \"uniqueSuccId\": 36688,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Type\": \"Predecessor\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"X09\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO116\",\n"
                        + "                            \"uniqueRoleId\": 111933\n"
                        + "                        }\n"
                        + "                    }\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"uniqueSuccId\": 36589,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Type\": \"Predecessor\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"T1430\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO189\",\n"
                        + "                            \"uniqueRoleId\": 136318\n"
                        + "                        }\n"
                        + "                    }\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        }\n"
                        + "    }\n"
                        + "}";
        var orgData = new JSONObject(singleRoleOrg);

        var dataExtractor = new JSONDataExtractor();
        var roleCodes = dataExtractor.getProspectiveOrgs(orgData);

        assert (roleCodes.isPresent());
        assert (roleCodes.get().getOrgName()).equals(expectedName);
    }

    @Test
    void returnsAnEmptyArrayIfAnOrgHasNoRoles() {
        String org =
                "{\n"
                        + "    \"Organisation\": {\n"
                        + "        \"Name\": \"COURTSIDE SURGERY\",\n"
                        + "        \"Date\": [\n"
                        + "            {\n"
                        + "                \"Type\": \"Operational\",\n"
                        + "                \"Start\": \"1974-04-01\"\n"
                        + "            }\n"
                        + "        ],\n"
                        + "        \"OrgId\": {\n"
                        + "            \"root\": \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "            \"extension\": \"L81024\"\n"
                        + "        },\n"
                        + "        \"Status\": \"Active\",\n"
                        + "        \"LastChangeDate\": \"2021-02-04\",\n"
                        + "        \"orgRecordClass\": \"RC1\",\n"
                        + "        \"GeoLoc\": {\n"
                        + "            \"Location\": {\n"
                        + "                \"AddrLn1\": \"KENNEDY WAY\",\n"
                        + "                \"AddrLn2\": \"YATE\",\n"
                        + "                \"Town\": \"BRISTOL\",\n"
                        + "                \"County\": \"AVON\",\n"
                        + "                \"PostCode\": \"BS37 4DQ\",\n"
                        + "                \"Country\": \"ENGLAND\",\n"
                        + "                \"UPRN\": 592571\n"
                        + "            }\n"
                        + "        },\n"
                        + "        \"Contacts\": {\n"
                        + "            \"Contact\": [\n"
                        + "                {\n"
                        + "                    \"type\": \"tel\",\n"
                        + "                    \"value\": \"01454 313874\"\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        },\n"
                        + "        \"Roles\": {\n"
                        + "            \"Role\": []\n"
                        + "        },\n"
                        + "        \"Rels\": {\n"
                        + "            \"Rel\": [\n"
                        + "                {\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2001-04-01\",\n"
                        + "                            \"End\": \"2013-03-31\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Inactive\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"5A3\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO179\",\n"
                        + "                            \"uniqueRoleId\": 101192\n"
                        + "                        }\n"
                        + "                    },\n"
                        + "                    \"id\": \"RE4\",\n"
                        + "                    \"uniqueRelId\": 263958\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"1999-04-01\",\n"
                        + "                            \"End\": \"2001-03-31\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Inactive\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"4YL81\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO171\",\n"
                        + "                            \"uniqueRoleId\": 137206\n"
                        + "                        }\n"
                        + "                    },\n"
                        + "                    \"id\": \"RE4\",\n"
                        + "                    \"uniqueRelId\": 263959\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2013-04-01\",\n"
                        + "                            \"End\": \"2018-03-31\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Inactive\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"12A\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO98\",\n"
                        + "                            \"uniqueRoleId\": 161525\n"
                        + "                        }\n"
                        + "                    },\n"
                        + "                    \"id\": \"RE4\",\n"
                        + "                    \"uniqueRelId\": 263960\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2018-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Active\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"15C\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO98\",\n"
                        + "                            \"uniqueRoleId\": 297755\n"
                        + "                        }\n"
                        + "                    },\n"
                        + "                    \"id\": \"RE4\",\n"
                        + "                    \"uniqueRelId\": 539679\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2019-10-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Active\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"U13456\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO272\",\n"
                        + "                            \"uniqueRoleId\": 388792\n"
                        + "                        }\n"
                        + "                    },\n"
                        + "                    \"id\": \"RE8\",\n"
                        + "                    \"uniqueRelId\": 616487\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        }\n"
                        + "    }\n"
                        + "}";

        var orgData = new JSONObject(org);

        var dataExtractor = new JSONDataExtractor();
        var roles = dataExtractor.getProspectiveOrgs(orgData);

        assert (roles.isEmpty());
    }

    @Test
    void returnsNoRoleCodeFromOrgDataWithoutValidRole() {
        String roleCode = "Not a GP or PCSE";
        String singleRoleOrg =
                "{\n"
                        + "    \"Organisation\": {\n"
                        + "        \"Name\": \"NHS ENGLAND - X26\",\n"
                        + "        \"Date\": [\n"
                        + "            {\n"
                        + "                \"Type\": \"Operational\",\n"
                        + "                \"Start\": \"2013-01-21\"\n"
                        + "            },\n"
                        + "            {\n"
                        + "                \"Type\": \"Legal\",\n"
                        + "                \"Start\": \"2013-04-01\"\n"
                        + "            }\n"
                        + "        ],\n"
                        + "        \"OrgId\": {\n"
                        + "            \"root\": \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "            \"extension\": \"X26\"\n"
                        + "        },\n"
                        + "        \"Status\": \"Active\",\n"
                        + "        \"LastChangeDate\": \"2023-01-31\",\n"
                        + "        \"orgRecordClass\": \"RC1\",\n"
                        + "        \"GeoLoc\": {\n"
                        + "            \"Location\": {\n"
                        + "                \"AddrLn1\": \"THE LEEDS GOVERNMENT HUB\",\n"
                        + "                \"AddrLn2\": \"7-8 WELLINGTON PLACE\",\n"
                        + "                \"Town\": \"LEEDS\",\n"
                        + "                \"PostCode\": \"LS1 4AP\",\n"
                        + "                \"Country\": \"ENGLAND\",\n"
                        + "                \"UPRN\": 72766088\n"
                        + "            }\n"
                        + "        },\n"
                        + "        \"Roles\": {\n"
                        + "            \"Role\": [\n"
                        + "                {\n"
                        + "                    \"id\": \""
                        + roleCode
                        + "\",\n"
                        + "                    \"uniqueRoleId\": 166234,\n"
                        + "                    \"primaryRole\": true,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2013-01-21\"\n"
                        + "                        },\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Active\"\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        },\n"
                        + "        \"Rels\": {\n"
                        + "            \"Rel\": [\n"
                        + "                {\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Operational\",\n"
                        + "                            \"Start\": \"2013-01-21\"\n"
                        + "                        },\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Status\": \"Active\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"XDH\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO126\",\n"
                        + "                            \"uniqueRoleId\": 128996\n"
                        + "                        }\n"
                        + "                    },\n"
                        + "                    \"id\": \"RE3\",\n"
                        + "                    \"uniqueRelId\": 189272\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        },\n"
                        + "        \"Succs\": {\n"
                        + "            \"Succ\": [\n"
                        + "                {\n"
                        + "                    \"uniqueSuccId\": 36688,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Type\": \"Predecessor\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"X09\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO116\",\n"
                        + "                            \"uniqueRoleId\": 111933\n"
                        + "                        }\n"
                        + "                    }\n"
                        + "                },\n"
                        + "                {\n"
                        + "                    \"uniqueSuccId\": 36589,\n"
                        + "                    \"Date\": [\n"
                        + "                        {\n"
                        + "                            \"Type\": \"Legal\",\n"
                        + "                            \"Start\": \"2013-04-01\"\n"
                        + "                        }\n"
                        + "                    ],\n"
                        + "                    \"Type\": \"Predecessor\",\n"
                        + "                    \"Target\": {\n"
                        + "                        \"OrgId\": {\n"
                        + "                            \"root\":"
                        + " \"2.16.840.1.113883.2.1.3.2.4.18.48\",\n"
                        + "                            \"assigningAuthorityName\": \"HSCIC\",\n"
                        + "                            \"extension\": \"T1430\"\n"
                        + "                        },\n"
                        + "                        \"PrimaryRoleId\": {\n"
                        + "                            \"id\": \"RO189\",\n"
                        + "                            \"uniqueRoleId\": 136318\n"
                        + "                        }\n"
                        + "                    }\n"
                        + "                }\n"
                        + "            ]\n"
                        + "        }\n"
                        + "    }\n"
                        + "}";
        var orgData = new JSONObject(singleRoleOrg);

        var dataExtractor = new JSONDataExtractor();
        var roleCodes = dataExtractor.getProspectiveOrgs(orgData);

        assert (roleCodes.isEmpty());
    }
}
