format_version: 4
pipelines:
  access-request-fulfilment.audit:
    group: access-request-fulfilment
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - documentation/*
    timer:
      spec: "*/3 * * * *"
    stages:
      - audit:
          clean_workspace: true
          approval: manual
          jobs:
            dependency_check_java:
              artifacts:
                - build:
                    source: app/build/reports
              tabs:
                dependency: reports/dependency-check-report.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks java-dependency-scan
            dependency_check_js:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks javascript-dependency-scan

