format_version: 4
pipelines:
  access-request-fulfillment.audit:
    group: repo-audit
    label_template: '${git[:8]}'
    materials:
      git:
        type: configrepo
        blacklist:
          - documentation/*
    timer:
      spec: '*/5 * * * *'
    stages:
      - audit:
          clean_workspace: true
          approval: manual
          jobs:
            dependency_check:
              artifacts:
                - build:
                    source: build/reports
              tabs:
                dependency: reports/dependency-check-report.html
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks java-dependency-scan
