format_version: 4
pipelines:
  "document-store-prototype":
    group: document-store
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - .git*
          - .idea/**/*.*
          - documentation/**/*.*
          - gradle/**/*.*
    stages:
      - build:
          clean_workspace: true
          jobs:
            build_backend:
              artifacts:
                - build:
                    source: app/build/libs
                    destination: jars
                - test:
                    source: app/build/test-results
                    destination: test-reports
              tasks:
                - exec:
                    command: dojo
                    arguments:
                      - "./gradlew app:build"
            build_ui:
              tasks:
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-node
                      - 'gocd/tasks.sh install-ui-dependencies'
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-node
                      - 'gocd/tasks.sh test-ui'
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-node
                      - 'gocd/tasks.sh build-ui'
      - deploy:
          clean_workspace: true
          jobs:
            terraform:
              artifacts:
                - build:
                    source: api_gateway_url_artifact
                    destination: properties
              tasks:
                - fetch:
                    stage: build
                    job: build_backend
                    source: jars
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-infra
                      - 'gocd/tasks.sh plan-deploy'
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-infra
                      - 'gocd/tasks.sh deploy'
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-infra
                      - 'gocd/tasks.sh extract-api-url'
      - testHarness:
          clean_workspace: true
          jobs:
            runTestHarness:
              environment_variables:
                API_AUTH: IAM
              artifacts:
                - test:
                    source: testHarness/build/test-results
                    destination: test-reports
              tasks:
                - fetch:
                    stage: deploy
                    job: terraform
                    source: properties
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-infra
                      - "gocd/tasks.sh export-aws-creds"
                - exec:
                    command: ls
                - exec:
                    command: dojo
                    arguments:
                      - "DOCUMENT_STORE_BASE_URI=$(cat properties/api_gateway_url_artifact) gocd/tasks.sh run-test-harness"
