format_version: 4
common:
  build_backend: &build_backend
    artifacts:
      - build:
          source: app/build/libs
          destination: jars
      - test:
          source: app/build/test-results
          destination: test-reports
    tasks:
      - exec:
          command: dojo
          arguments:
            - "./gradlew app:build"
  deploy_terraform: &deploy_terraform
    artifacts:
      - build:
          source: api_gateway_url_artifact
          destination: properties
      - build:
          source: cognito_user_pool_ids_artifact
          destination: properties
      - build:
          source: cognito_client_ids_artifact
          destination: properties
      - build:
          source: amplify_app_ids_artifact
          destination: properties
    tasks:
      - fetch:
          stage: build_backend
          job: build
          source: jars
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks tf_plan
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks tf_apply
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks extract-raw-terraform-output api_gateway_url
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks extract-json-terraform-output cognito_user_pool_ids
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks extract-json-terraform-output cognito_client_ids
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks extract-json-terraform-output amplify_app_ids
  build_ui: &build_ui
    artifacts:
      - build:
          source: ui/ui.tgz
          destination: tars
    tasks:
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-node
            - ./tasks install-ui-dependencies
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks configure-ui
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-node
            - ./tasks build-ui
  unit_test_ui: &unit_test_ui
    tasks:
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-node
            - ./tasks test-ui
  deploy_ui: &deploy_ui
    tasks:
      - fetch:
          stage: build_ui
          job: build
          source: tars
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks deploy-ui
  e2e_test: &e2e_test
    tasks:
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-infra
            - ./tasks configure-e2e-tests
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-node
            - ./tasks install-ui-dependencies && ./tasks run-e2e-tests

pipelines:
  "paperless-record-service.dev":
    group: paperless-record-service
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - .git*
          - .idea/**/*.*
          - documentation/**/*.*
          - gradle/**/*.*
    stages:
      - build_backend:
          clean_workspace: true
          jobs:
            build: *build_backend
      - deploy_backend:
          environment_variables:
            ENVIRONMENT: dev
          clean_workspace: true
          jobs:
            terraform: *deploy_terraform

      - testHarness:
          clean_workspace: true
          jobs:
            runTestHarness:
              environment_variables:
                ENVIRONMENT: dev
                API_AUTH: IAM
              artifacts:
                - test:
                    source: testHarness/build/test-results
                    destination: test-reports
              tasks:
                - fetch:
                    stage: deploy_backend
                    job: terraform
                    source: properties
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-infra
                      - ./tasks export-aws-creds
                - exec:
                    command: ls
                - exec:
                    command: dojo
                    arguments:
                      - "DOCUMENT_STORE_BASE_URI=$(cat properties/api_gateway_url_artifact) COGNITO_USER_POOL_IDS=\"$(cat properties/cognito_user_pool_ids_artifact)\" COGNITO_CLIENT_IDS=\"$(cat properties/cognito_client_ids_artifact)\" ./tasks run-test-harness"
      - build_ui:
          environment_variables:
            ENVIRONMENT: dev
          clean_workspace: true
          jobs:
            build: *build_ui
            unit-test-ui: *unit_test_ui

      - deploy_ui:
          environment_variables:
            ENVIRONMENT: dev
          clean_workspace: true
          jobs:
            deploy: *deploy_ui

      - e2e_tests:
          environment_variables:
            ENVIRONMENT: dev
          clean_workspace: true
          jobs:
            e2e-tests: *e2e_test


  "paperless-record-service.pre-prod":
    group: paperless-record-service
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - .git*
          - .idea/**/*.*
          - documentation/**/*.*
          - gradle/**/*.*
      dev_env:
        pipeline: paperless-record-service.dev
        stage: deploy_ui
    stages:
      - build_backend:
          clean_workspace: true
          jobs:
            build: *build_backend

      - deploy_backend:
          environment_variables:
            ENVIRONMENT: pre-prod
          clean_workspace: true
          jobs:
            terraform: *deploy_terraform
      - testHarness:
          clean_workspace: true
          jobs:
            runTestHarness:
              environment_variables:
                ENVIRONMENT: pre-prod
                API_AUTH: IAM
              artifacts:
                - test:
                    source: testHarness/build/test-results
                    destination: test-reports
              tasks:
                - fetch:
                    stage: deploy_backend
                    job: terraform
                    source: properties
                - exec:
                    command: dojo
                    arguments:
                      - -c
                      - Dojofile-infra
                      - ./tasks export-aws-creds
                - exec:
                    command: ls
                - exec:
                    command: dojo
                    arguments:
                      - "DOCUMENT_STORE_BASE_URI=$(cat properties/api_gateway_url_artifact) COGNITO_USER_POOL_IDS=\"$(cat properties/cognito_user_pool_ids_artifact)\" COGNITO_CLIENT_IDS=\"$(cat properties/cognito_client_ids_artifact)\" ./tasks run-test-harness"
      - build_ui:
          environment_variables:
            ENVIRONMENT: pre-prod
          clean_workspace: true
          jobs:
            build: *build_ui
            unit-test-ui: *unit_test_ui
      - deploy_ui:
          environment_variables:
            ENVIRONMENT: pre-prod
          clean_workspace: true
          jobs:
            deploy: *deploy_ui
      - e2e_tests:
          environment_variables:
            ENVIRONMENT: pre-prod
          clean_workspace: true
          jobs:
            e2e-tests: *e2e_test