format_version: 4
pipelines:
  "document-store-prototype":
    group: document-store
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - .git*
          - .idea/**/*.*
          - documentation/**/*.*
          - gradle/**/*.*
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              artifacts:
                - build:
                    source: app/build/libs
                    destination: jars
                - test:
                    source: app/build/test-results
                    destination: test-reports
              tasks:
                - exec:
                    command: dojo
                    arguments:
                      - "./gradlew build"
      - deploy:
          clean_workspace: true
          jobs:
            terraform:
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: jars
                - exec:
                    command: dojo
                    working_directory: terraform
                    arguments:
                      - -c
                      - ../Dojofile-infra
                      - "terraform init"
                - exec:
                    command: dojo
                    working_directory: terraform
                    arguments:
                      - -c
                      - ../Dojofile-infra
                      - "terraform plan -var lambda_jar_filename=app.jar -out=statefile"
                - exec:
                    command: dojo
                    working_directory: terraform
                    arguments:
                      - -c
                      - ../Dojofile-infra
                      - "terraform apply statefile"
