format_version: 4
common:
  backend: &build_backend
    artifacts:
      - build:
          source: app/build/libs
          destination: jars
      - test:
          source: app/build/test-results
          destination: test-reports
      - build:
          source: app/build/distributions
          destination: jars
    tasks:
      - exec:
          command: dojo
          arguments:
            - ./gradlew app:build;
              ./gradlew app:buildZip;
  lambdas: &build_lambdas
    artifacts:
      - build:
          source: lambdas/CreateDocumentManifestByNhsNumber/build/libs
          destination: jars
      - build:
          source: lambdas/CreateDocumentReference/build/libs
          destination: jars
      - build:
          source: lambdas/DeleteDocumentReference/build/libs
          destination: jars
      - build:
          source: lambdas/DocumentReferenceSearch/build/libs
          destination: jars
      - build:
          source: lambdas/FakeVirusScannedEvent/build/libs
          destination: jars
      - build:
          source: lambdas/ReRegistrationEvent/build/libs
          destination: jars
      - build:
          source: lambdas/SearchPatientDetails/build/libs
          destination: jars
      - build:
          source: lambdas/VirusScannedEvent/build/libs
          destination: jars
    tasks:
      - exec:
          command: dojo
          arguments:
            - ./gradlew lambdas:CreateDocumentManifestByNhsNumber:build;
              ./gradlew lambdas:CreateDocumentReference:build;
              ./gradlew lambdas:DeleteDocumentReference:build;
              ./gradlew lambdas:DocumentReferenceSearch:build;
              ./gradlew lambdas:FakeVirusScannedEvent:build;
              ./gradlew lambdas:ReRegistrationEvent:build;
              ./gradlew lambdas:SearchPatientDetails:build;
              ./gradlew lambdas:VirusScannedEvent:build;
  authoriser: &authoriser
    artifacts:
      - build:
          source: authoriser/build/libs
          destination: jars
      - test:
            source: authoriser/build/test-results
            destination: test-reports
    tasks:
      - exec:
          command: dojo
          arguments:
            - "./gradlew authoriser:build"
  plan_terraform: &plan_terraform
    artifacts:
      - build:
          source: terraform/tfplan
          destination: terraform/
    tasks:
      - fetch:
          stage: build
          job: backend
          source: jars
      - fetch:
          stage: build
          job: authoriser
          source: jars
      - fetch:
          stage: build
          job: lambdas
          source: jars
      - exec:
          command: dojo
          arguments:
            - ./scripts/tasks.sh tf_plan
  deploy_terraform: &deploy_terraform
    tasks:
      - fetch:
          stage: plan_terraform
          job: plan
          source: terraform/tfplan
          destination: terraform/
          is_file: yes
      - fetch:
          stage: build
          job: backend
          source: jars
      - fetch:
          stage: build
          job: lambdas
          source: jars
      - fetch:
          stage: build
          job: authoriser
          source: jars
      - exec:
          command: dojo
          arguments:
            - ./scripts/tasks.sh tf_apply
  deploy_ui: &deploy_ui
    tasks:
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-node
            - ./scripts/tasks.sh install-ui-dependencies
      - exec:
          command: dojo
          arguments:
            - ./scripts/tasks.sh configure-ui
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-node
            - ./scripts/tasks.sh test-ui
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-node
            - ./scripts/tasks.sh build-ui
      - exec:
          command: dojo
          arguments:
            - ./scripts/tasks.sh deploy-ui
    timeout: 30
  e2e_test: &e2e_test
    tasks:
      - exec:
          command: dojo
          arguments:
            - ./scripts/tasks.sh configure-e2e-test
      - exec:
          command: dojo
          arguments:
            - -c
            - Dojofile-node
            - ./scripts/tasks.sh install-e2e-test-dependencies && ./scripts/tasks.sh run-e2e-test
    artifacts:
      - test:
          source: e2eTest/cypress/screenshots
      - test:
          source: e2eTest/cypress/videos
pipelines:
  "access-request-fulfilment.dev":
    group: access-request-fulfilment
    label_template: "${git[:8]}"
    lock_behavior: "unlockWhenFinished"
    materials:
      git:
        type: configrepo
        blacklist:
          - .git*
          - .idea/**/*.*
          - docs/**/*.*
          - gradle/**/*.*
          - virusScanner/**/*.*
          - gocd/virus.scanner.build.gocd.yaml
    stages:
      - build:
          environment_variables:
            ENVIRONMENT: dev
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            backend: *build_backend
            authoriser: *authoriser
            lambdas: *build_lambdas
      - plan_terraform:
          environment_variables:
            WORKSPACE: dev
            ENVIRONMENT: dev
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            plan: *plan_terraform
      - deploy_terraform:
          environment_variables:
            WORKSPACE: dev
            ENVIRONMENT: dev
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            apply: *deploy_terraform
      - deploy_ui:
          environment_variables:
            ENVIRONMENT: dev
            WORKSPACE: dev
            NHS_CIS2_ENVIRONMENT: development
            OIDC_PROVIDER_ID: "cis2devoidc"
          clean_workspace: true
          jobs:
            deploy: *deploy_ui
      - app_integration_tests:
          environment_variables:
            ENVIRONMENT: dev
            WORKSPACE: dev
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            test:
              artifacts:
                - test:
                    source: lambdas/CreateDocumentManifestByNhsNumber/build/test-results
                    destination: test-reports/lambdas
                - test:
                    source: lambdas/CreateDocumentReference/build/test-results
                    destination: test-reports/lambdas
                - test:
                    source: lambdas/DeleteDocumentReference/build/test-results
                    destination: test-reports/lambdas
                - test:
                    source: lambdas/DocumentReferenceSearch/build/test-results
                    destination: test-reports/lambdas
                - test:
                    source: lambdas/FakeVirusScannedEvent/build/test-results
                    destination: test-reports/lambdas
                - test:
                    source: lambdas/ReRegistrationEvent/build/test-results
                    destination: test-reports/lambdas
                - test:
                    source: lambdas/SearchPatientDetails/build/test-results
                    destination: test-reports/lambdas
                - test:
                    source: lambdas/VirusScannedEvent/build/test-results
                    destination: test-reports/lambdas
                - test:
                    source: authoriser/build/test-results
                    destination: test-reports/authoriser
              tasks:
                - exec:
                    command: dojo
                    arguments:
                      - ./scripts/tasks.sh run-integration-test
      - e2e_tests:
          environment_variables:
            WORKSPACE: dev
            ENVIRONMENT: dev
            NHS_CIS2_ENVIRONMENT: development
            OIDC_PROVIDER_ID: "cis2devoidc"
          clean_workspace: true
          jobs:
            e2e-test: *e2e_test
  "access-request-fulfilment.pre-prod":
    group: access-request-fulfilment
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - .git*
          - .idea/**/*.*
          - docs/**/*.*
          - gradle/**/*.*
          - virusScanner/**/*.*
          - gocd/virus.scanner.build.gocd.yaml
      dev_env:
        pipeline: access-request-fulfilment.dev
        stage: e2e_tests
    stages:
      - build:
          environment_variables:
            ENVIRONMENT: pre-prod
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            backend: *build_backend
            authoriser: *authoriser
            lambdas: *build_lambdas
      - plan_terraform:
          environment_variables:
            ENVIRONMENT: pre-prod
            WORKSPACE: pre-prod
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            plan: *plan_terraform
      - deploy_terraform:
          approval:
            type: manual
            allow_only_on_success: true
          environment_variables:
            ENVIRONMENT: pre-prod
            WORKSPACE: pre-prod
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            apply: *deploy_terraform
      - deploy_ui:
          environment_variables:
            ENVIRONMENT: pre-prod
            WORKSPACE: pre-prod
            NHS_CIS2_ENVIRONMENT: development
            OIDC_PROVIDER_ID: "cis2devoidc"
          clean_workspace: true
          jobs:
            deploy: *deploy_ui
#      - e2e_tests:
#          environment_variables:
#            ENVIRONMENT: pre-prod
#            WORKSPACE: pre-prod
#            NHS_CIS2_ENVIRONMENT: development
#            OIDC_PROVIDER_ID: "cis2devoidc"
#          clean_workspace: true
#          jobs:
#            e2e-test: *e2e_test
  "access-request-fulfilment.prod":
    group: access-request-fulfilment
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
        blacklist:
          - .git*
          - .idea/**/*.*
          - docs/**/*.*
          - gradle/**/*.*
          - virusScanner/**/*.*
          - gocd/virus.scanner.build.gocd.yaml
      pre_prod_env:
        pipeline: access-request-fulfilment.pre-prod
        stage: e2e_tests
    stages:
      - build:
          environment_variables:
            ENVIRONMENT: prod
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            backend: *build_backend
            authoriser: *authoriser
            lambdas: *build_lambdas
      - plan_terraform:
          environment_variables:
            ENVIRONMENT: prod
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            plan: *plan_terraform
      - deploy_terraform:
          approval:
            type: manual
            allow_only_on_success: true
          environment_variables:
            ENVIRONMENT: prod
            NHS_CIS2_ENVIRONMENT: development
          clean_workspace: true
          jobs:
            apply: *deploy_terraform
      - deploy_ui:
          environment_variables:
            ENVIRONMENT: prod
            OIDC_PROVIDER_ID: "COGNITO"
          clean_workspace: true
          jobs:
            deploy: *deploy_ui
